site_name: Novel Downloader
repo_url: https://github.com/PauloHFS/novel-downloader
repo_name: PauloHFS/novel-downloader
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR

markdown_extensions:
  - attr_list
  # - admonition
  # - codehilite
  # - toc:
      # permalink: true

extra_css:
  - stylesheets/extra.css

plugin:
  - mkdocstrings:
    handlers:
      python:
        paths: [src]